homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.7325
  longitude: -84.5555
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 860
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit

#camera:
#  - platform: local_file
#    name: Microsoft HDCam
#    file_path: /tmp/lastsnap.jpg

#camera:
#  - platform: ffmpeg
#    input: rtsp://admin:20160404@192.168.1.14/onvif2
#    name: Outside Cam

#camera 2:
#  - platform: ffmpeg
#    input: rtsp://admin:20160404@192.168.1.13/onvif2
#    name: Inside Cam

ecobee:
  api_key: !secret ecobee_api_key

#image_processing:
#  - platform: microsoft_face_detect
#    source:
#      - entity_id: camera.microsoft_hdcam

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:


# Example configuration.yaml entry
weblink:
  entities:
    - name: Router
      url: http://192.168.1.1/
    - name: Home Assistant
      url: https://home-assistant.io

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_pass
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: m12.cloudmqtt.com
  port: 14853
  #keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass
  #protocol: 3.1

sensor:
  - platform: yr
  - platform: cpuspeed
    name: AMDFX
    # Sonoff Program v4.1.1 
    # Sample raw output from sensor {"Time":"2017-04-06T23:23:41", "AM2301":{"Temperature":6.1, "Humidity":87.2}}
  - platform: mqtt
    name: "Basement Room Temp"
    state_topic: "tele/home/sonoff/basement/SENSOR"
    value_template: '{{ value_json.AM2301.Temperature }}'
    qos: 1
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Basement Humidity"
    state_topic: "tele/home/sonoff/basement/SENSOR"
    qos: 1
    unit_of_measurement: "%"
    value_template: '{{ value_json.AM2301.Humidity }}'

  - platform: mqtt
    name: "Outside Temp"
    state_topic: "tele/home/sonoff/outside/SENSOR"
    value_template: '{{ value_json.AM2301.Temperature }}'
    qos: 1
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Outside Humidity"
    state_topic: "tele/home/sonoff/outside/SENSOR"
    qos: 1
    unit_of_measurement: "%"
    value_template: '{{ value_json.AM2301.Humidity }}'

# Text to speech
tts:
  platform: google

notify:
  - name: FileOut
    platform: file
    filename: /tmp/Kat_home.txt

switch:
  - platform: mqtt
    name: "Outside"
    state_topic: "stat/home/sonoff/outside/POWER"
    command_topic: "cmnd/DVES_9F227C/POWER"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Basement"
    state_topic: "stat/home/sonoff/basement/POWER"
    command_topic: "cmnd/DVES_9F9F65/POWER"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
group: !include groups.yaml
device_tracker: !include device_tracker.yaml
#automation: !include automation.yaml 
logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug

zwave:
  usb_path: /dev/ttyACM0
